# Generated by Django 4.0.9 on 2023-03-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CL', 'Client'), ('TR', 'Trainer')], default='CL', max_length=2),
        ),
    ]
