- search: /^# Standard Library/
  insensitive: true
  replacement: ''
- search: /^# Project Libraries/
  insensitive: true
  replacement: ''
- search: /^# Project Libraries/
  insensitive: true
  replacement: ''
