version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    container_name: fitness-djagno
    ports:
      - "8000:8000"
    volumes:
      - ./base:/base
    command: compose/local-env/django/entrypoint.sh
    env_file:
      - ./base/.envs/.local/.django
      - ./base/.envs/.local/.postgres
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: fitness-db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./base/.envs/.local/.postgres

  mailhog:
    image: mailhog/mailhog:latest
    container_name: fitness-mailhog
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"
